### ISSUE TITLE
error while parsing the chunk

### ISSUE THREAD

**Issue by aaajain** [jed/dynamo-client#12]
Hi,

I an facing error response from dynamo-client while using query. The error response comes very often. But, sometimes I get a proper response also. So, its not a data issue. I get error in dynamo-client, when it parses the json response.

[2017-05-11 21:10:18:701]  SyntaxError: Unexpected token S
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/chenoa/Desktop/02-05-2017/v4api_07_20_16/v4api/node_modules/dynamo-client/dynamo_client.js:92:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
[2017-05-11 21:10:18:702]  Error while using query: SyntaxError: Unexpected token S
[2017-05-11 21:10:18:728]  Error: HTTP/1.1 200 

Is it that, response is yet not completed and the control moved to res.end method or is it something to do with concurrency.
The issue des not happen always but, it does happen very frequently.

Thanks.

**Comment by jed** [comment]
sorry for the trouble you're having, i encourage you to use [AWS's library](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) instead.

**Comment by aaajain** [comment]
Thanks Jed for prompt replay. We may not be able to migrate right away. I fixed it by using the 'readable' event instead of 'data' and it worked for me.

_res.on("**readable**", function(){
      var chunk;
      while (null !== (chunk = res.read())) {
          json += chunk
      }_

The issue is that npm install dynamo-client removes the above code. 
Thanks again.
